{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "helm-foo.serviceAccountName" . }}
  labels:
{{ include "helm-foo.labels" . | indent 4 }}
{{- end -}}
